export const defs = svg => {
  const svgDefs = svg.append('defs');
  svgDefs.append('pattern')
      .attr('id', 'pattern-available')
      .attr('width', '3')
      .attr('height', '3')
      .attr('patternUnits', 'userSpaceOnUse')
      .attr('patternTransform', 'rotate(45)')
      .append('rect')
        .attr('width', '2')
        .attr('height', '3')
        .attr('transform', 'translate(0,0)')
        .attr('fill', 'white')
      ;
  svgDefs.append('mask')
      .attr('id', 'mask-available')
      .append('rect')
        .attr('x', '0')
        .attr('y', '0')
        .attr('width', '100%')
        .attr('height', '100%')
        .attr('fill', 'url(#pattern-available)')
      ;
  svgDefs.append('pattern')
      .attr('id', 'pattern-ledger')
      .attr('width', '3')
      .attr('height', '3')
      .attr('patternUnits', 'userSpaceOnUse')
      .attr('patternTransform', 'rotate(90)')
      .append('rect')
        .attr('width', '2')
        .attr('height', '3')
        .attr('transform', 'translate(0,0)')
        .attr('fill', 'white')
      ;
  svgDefs.append('mask')
      .attr('id', 'mask-ledger')
      .append('rect')
        .attr('x', '0')
        .attr('y', '0')
        .attr('width', '100%')
        .attr('height', '100%')
        .attr('fill', 'url(#pattern-ledger)')
      ;
  svgDefs.append('pattern')
      .attr('id', 'pattern-booked')
      .attr('width', '3')
      .attr('height', '3')
      .attr('patternUnits', 'userSpaceOnUse')
      .attr('patternTransform', 'rotate(135)')
      .append('rect')
        .attr('width', '2')
        .attr('height', '3')
        .attr('transform', 'translate(0,0)')
        .attr('fill', 'white')
      ;
  svgDefs.append('mask')
      .attr('id', 'mask-booked')
      .append('rect')
        .attr('x', '0')
        .attr('y', '0')
        .attr('width', '100%')
        .attr('height', '100%')
        .attr('fill', 'url(#pattern-booked)')
      ;
};
